'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { SeriesChart } from '@packages/components/analytics';
import axios from 'apps/admin-ui/src/utils/axioInstance';

const control = 'bg-slate-900 border border-slate-600 rounded p-3';
const allowed: Record<string, string[]> = { Pending: ['Confirmed', 'Cancelled'], Confirmed: ['Processing', 'Cancelled'], Processing: ['Shipped'], Shipped: ['Delivered'], Delivered: ['Returned'] };
export default function Operations({ mode }: { mode: 'dashboard-stats' | 'orders' | 'notifications' | 'payments' | 'logs' }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [status, setStatus] = useState(''); const [shopId, setShopId] = useState('');
  const [action, setAction] = useState(''); const [userId, setUserId] = useState(''); const [page, setPage] = useState(1); const [after, setAfter] = useState('');
  const [selected, setSelected] = useState<any>(null); const [nextStatus, setNextStatus] = useState(''); const [trackingNumber, setTrackingNumber] = useState(''); const [estimatedDelivery, setEstimatedDelivery] = useState(''); const [error, setError] = useState('');
  const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [audience, setAudience] = useState('users'); const [recipientId, setRecipientId] = useState(''); const [broadcast, setBroadcast] = useState(false);
  const client = useQueryClient();
  const params = new URLSearchParams({ page: String(page), ...(from ? { from } : {}), ...(to ? { to } : {}), ...(status ? { status } : {}), ...(shopId ? { shopId } : {}), ...(action ? { action } : {}), ...(userId ? { userId } : {}), ...(after ? { after } : {}) }).toString();
  const query = useQuery({ queryKey: ['admin-ops', mode, params], queryFn: async () => (await axios.get(`/admin/${mode}?${params}`)).data });
  const mutation = useMutation({ mutationFn: async (kind: string) => {
    if (kind === 'status') return axios.patch(`/admin/update-order-status/${selected.id}`, { status: nextStatus, trackingNumber, estimatedDelivery });
    if (kind === 'refund') return axios.post(`/admin/refund/${selected.stripePaymentId}`, { orderId: selected.id });
    return axios.post('/admin/send-notification', { title, message, audience, recipientId, confirmBroadcast: broadcast });
  }, onSuccess: () => { setSelected(null); client.invalidateQueries({ queryKey: ['admin-ops'] }); } });
  const download = async (format: string) => { try { const { data } = await axios.get(`/admin/logs?${params}&format=${format}`, { responseType: 'blob' }); const url = URL.createObjectURL(data); const a = document.createElement('a'); a.href = url; a.download = `logs.${format}`; a.click(); URL.revokeObjectURL(url); } catch { setError('Export failed'); } };
  const data = query.data;
  return <main className="p-5 sm:p-8 text-white space-y-6"><h1 className="text-2xl font-bold capitalize">{mode.replaceAll('-', ' ')}</h1>{mode !== 'notifications' && <div className="flex flex-wrap gap-3"><label>From<input className={`block ${control}`} type="date" value={from} onChange={e => { setFrom(e.target.value); setPage(1); setAfter(''); }} /></label><label>To<input className={`block ${control}`} type="date" value={to} onChange={e => { setTo(e.target.value); setPage(1); setAfter(''); }} /></label>{['orders', 'payments'].includes(mode) && <label>Shop ID<input className={`block ${control}`} value={shopId} onChange={e => { setShopId(e.target.value); setPage(1); }} /></label>}{mode === 'orders' && <label>Status<select className={`block ${control}`} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All</option>{['Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Returned', 'Refunded'].map(s => <option key={s}>{s}</option>)}</select></label>}{mode === 'logs' && <><label>Action<input className={`block ${control}`} value={action} onChange={e => { setAction(e.target.value); setPage(1); }} /></label><label>User ID<input className={`block ${control}`} value={userId} onChange={e => { setUserId(e.target.value); setPage(1); }} /></label><button onClick={() => download('csv')}>Export CSV</button><button onClick={() => download('json')}>Export JSON</button></>}</div>}{query.isLoading && <p>Loading…</p>}{query.isError && <p role="alert">Unable to load data. Check filters and service availability. <button onClick={() => query.refetch()}>Retry</button></p>}{(mutation.isError || error) && <p role="alert" className="text-red-400">{error || (mutation.error as any)?.response?.data?.message || 'Operation failed'}</p>}{mutation.isSuccess && <p role="status" className="text-green-400">Saved successfully.</p>}
    {mode === 'dashboard-stats' && data && <><div className="grid grid-cols-2 md:grid-cols-3 gap-4">{Object.entries(data.stats).map(([key, value]) => <article className="rounded-xl border border-slate-700 p-5" key={key}><h2>{key}</h2><p className="text-2xl">{Number(value).toLocaleString()}</p></article>)}</div><h2>System revenue</h2><SeriesChart rows={data.timeline} fields={['revenue']} /><h2>New registrations</h2><SeriesChart rows={data.timeline} fields={['users', 'sellers']} /><h2>Best selling products</h2>{data.topProducts.map((p: any) => <p key={p.id}>{p.title} · {p.quantity} sold · ${Number(p.totalPrice).toFixed(2)}</p>)}</>}
    {mode === 'orders' && data && <><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{['Order', 'Buyer', 'Shop', 'Amount', 'Status', 'Details'].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.orders.map((o: any) => <tr className="border-t border-slate-700" key={o.id}><td className="p-3">{o.orderNumber}</td><td>{o.user.name}</td><td>{o.shop.name}</td><td>${o.totalAmount.toFixed(2)}</td><td>{o.status}</td><td><button className="p-3 text-blue-400" onClick={() => { setSelected(o); setNextStatus(allowed[o.status]?.[0] ?? ''); setTrackingNumber(o.trackingNumber || ''); setEstimatedDelivery(o.estimatedDelivery?.slice(0, 10) || ''); }}>View / Update</button></td></tr>)}</tbody></table></div>{!data.orders.length && <p>No matching orders.</p>}</>}
    {mode === 'notifications' && <><form className="space-y-3 max-w-2xl" onSubmit={e => { e.preventDefault(); mutation.mutate('send'); }}><h2 className="text-xl">Send system notification</h2><label className="block">Title<input className={`block w-full ${control}`} required maxLength={150} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block">Message<textarea className={`block w-full ${control}`} required maxLength={3000} value={message} onChange={e => setMessage(e.target.value)} /></label><label>Audience<select className={control} value={audience} onChange={e => setAudience(e.target.value)}><option>users</option><option>sellers</option></select></label><label className="block">Recipient ID (leave empty for all)<input className={`block w-full ${control}`} value={recipientId} onChange={e => setRecipientId(e.target.value)} /></label>{!recipientId && <label className="block"><input type="checkbox" required checked={broadcast} onChange={e => setBroadcast(e.target.checked)} /> Send to all {audience}</label>}<button disabled={mutation.isPending} className="bg-blue-600 rounded px-5 py-3">Send notification</button></form><h2 className="text-xl">Notifications</h2>{data?.notifications.map((n: any) => <article className="border-b border-slate-700 py-3" key={n.id}><strong>{n.title}</strong><p>{n.message}</p><time>{new Date(n.createdAt).toLocaleString()}</time></article>)}</>}
    {mode === 'payments' && data && <><h2 className="text-xl">Stripe payments</h2>{data.payments.map((p: any) => <article className="border-b border-slate-700 py-3" key={p.id}>{p.id} · {p.amount.toFixed(2)} {p.currency.toUpperCase()} · {p.status}</article>)}<div className="flex gap-4"><button disabled={!after} onClick={() => setAfter('')}>First page</button><button disabled={!data.hasMore} onClick={() => setAfter(data.nextCursor)}>More payments</button></div><h2 className="text-xl">Revenue by shop</h2>{data.byShop.map((s: any, i: number) => <p key={i}>{s.name} · ${s.revenue.toFixed(2)} · {s.orders} orders</p>)}<SeriesChart rows={data.timeline} fields={['revenue']} /><h2 className="text-xl">Refund eligible orders</h2>{data.orders.filter((o: any) => o.paymentStatus === 'Paid' && ['Cancelled', 'Returned'].includes(o.status)).map((o: any) => <div className="flex flex-wrap justify-between py-3" key={o.id}><span>{o.orderNumber} · {o.shop.name} · ${o.totalAmount.toFixed(2)} {o.refundState ? `· Refund ${o.refundState}` : ''}</span><button onClick={() => setSelected(o)} className="text-amber-400">Review refund</button></div>)}</>}
    {mode === 'logs' && data && <><SeriesChart rows={data.timeline} fields={['views', 'cartAdds', 'purchases']} />{data.chartTruncated && <p>Chart limited to 50,000 events; narrow the date range.</p>}<p>Exports include all events matching the current filters.</p>{data.logs.map((log: any) => <article className="border-b border-slate-700 py-3 break-words" key={log.id}><time>{new Date(log.createdAt).toLocaleString()}</time> · {log.action} · {log.userId || 'Anonymous'}<p>{log.message}</p><details><summary>Metadata</summary><pre className="overflow-x-auto">{JSON.stringify(log.metadata, null, 2)}</pre></details></article>)}</>}
    {data?.total !== undefined && <div className="flex gap-4"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} · {data.total} results</span><button disabled={page * 20 >= data.total} onClick={() => setPage(page + 1)}>Next</button></div>}
    {selected && <div className="fixed inset-0 z-50 bg-black/70 p-4 flex justify-center items-center"><section role="dialog" aria-modal="true" aria-label="Order details" className="bg-slate-900 rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto space-y-4"><button className="float-right p-2" onClick={() => setSelected(null)}>Close</button><h2 className="text-xl">{selected.orderNumber}</h2>{mutation.isError && <p role="alert" className="text-red-400">{(mutation.error as any)?.response?.data?.message || 'Operation failed'}</p>}<p>{selected.status} · {selected.paymentStatus} · ${selected.totalAmount.toFixed(2)}</p><p>{selected.user?.name} {selected.user?.email}</p><h3>Shipping address</h3><p>{Object.values(selected.shippingAddress ?? {}).filter(v => typeof v === 'string').join(', ')}</p>{selected.items?.map((item: any) => <p key={item.id}>{item.title} × {item.quantity} · ${item.totalPrice.toFixed(2)}</p>)}{mode === 'orders' && nextStatus && <form className="space-y-3" onSubmit={e => { e.preventDefault(); mutation.mutate('status'); }}><label>Status<select className={`block ${control}`} value={nextStatus} onChange={e => setNextStatus(e.target.value)}>{allowed[selected.status]?.map(s => <option key={s}>{s}</option>)}</select></label><label className="block">Tracking number<input className={`block w-full ${control}`} value={trackingNumber} onChange={e => setTrackingNumber(e.target.value)} /></label><label className="block">Estimated delivery<input className={`block ${control}`} type="date" value={estimatedDelivery} onChange={e => setEstimatedDelivery(e.target.value)} /></label><button disabled={mutation.isPending} className="bg-blue-600 p-3 rounded">Update status</button></form>}{mode === 'payments' && <><p>Refund ${selected.totalAmount.toFixed(2)} for this order to the original payment method.</p><button disabled={mutation.isPending} onClick={() => mutation.mutate('refund')} className="bg-red-700 rounded p-3">Confirm refund</button></>}</section></div>}
  </main>;
}

